### ISSUE TITLE
A Few Questions

### ISSUE THREAD

**Issue by WindowsNinetyTen** [SwareJonge/mkdd#11]
I have a few questions about this project:

*Does this make a playable executable file?
*How do I get GC MW per the instructions?
*Where do I get DevKit Pro?

**Comment by SwareJonge** [comment]
I'll try and do my best to answer every question as clear as possible and update the Readme later on so it's clear for everyone.
1: Yes, this produces a .dol file that's identical to the original
2: You can get the compilers [here](https://files.decomp.dev/compilers_latest.zip) 
3: You can get devkitPro [here](https://devkitpro.org/wiki/Getting_Started), the only requirement is devkitPPC

**Comment by WindowsNinetyTen** [comment]
Thank you. I was referring to making an exe file that can natively run on Windows without an emulator.

**Comment by SwareJonge** [comment]
Unfortunately this project is quite far from that being possible and most likely won't be able to either

**Comment by WindowsNinetyTen** [comment]
However, somebody _could_ try to port it to PC by reverse engineering the code and turning the instructions into x86 ones.
