### ISSUE TITLE
Not an issue. Just a notice to a bounty.

### ISSUE THREAD

**Issue by Sir-LoLz** [SwareJonge/mkdd#7]
A bounty has been out for MKDD and is at $3,000 in order to improve the LAN mode for MKDD. And thought it might interest you.

Regardless I plan to work towards it myself. However, my understanding of assembly is nonexistent. I am working towards understanding it. There are great guides out there. But I started the bounty with the hopes that someone more knowing of the process would beat me to a solution. Either way I refuse to claim the bounty as I am the one who started it. making it a clear conflict of interest, lol.

Whether or not is fine. As mentioned, I plan to keep working on it. and I may add to this once I become more comfortable with the process. I just brought it up in case the bounty might interest you. Feel free to ask questions if you have any.

Thanks.

https://app.bountysource.com/issues/91924449-a-fix-to-the-lan-code

**Comment by SwareJonge** [comment]
I've been aware of the bounty however I'm not interested myself in going through the process of creating a patcher, rewrite the code (etc. etc.). I hope my decomp will be of any help when I'm going to start working on the LAN mode side.

**Comment by Sir-LoLz** [comment]
ah ok. sorry to bring it up again then.

**Comment by Proryanator** [comment]
@SwareJonge hey there! Have you gotten to any LAN stuff yet? 😊

**Comment by SwareJonge** [comment]
Fixing the LAN Code isn't a goal for this project and will never be, there are other projects that'll try to tackle this.
